apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-register-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/iam-arellano/gitops-register-app
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
